### ISSUE TITLE
does 1D Barcode Detect and Decode  support  many barcodes in one pic?

### ISSUE THREAD

**Issue by ArlanCooper** [opencv/opencv_contrib#3449]
##### System information (version)

- OpenCV => :grey_question:
- Operating System / Platform => :grey_question:
- Compiler => :grey_question:

##### Detailed description
does 1D Barcode Detect and Decode  support  many barcodes in one pic?
##### Issue submission checklist

 - [ ] I report the issue, it's not a question
   
 - [x] I checked the problem with documentation, FAQ, open issues,
       forum.opencv.org, Stack Overflow, etc and have not found any solution
   
 - [ ] I updated to the latest OpenCV version and the issue is still there
   
 - [ ] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by mshabunin** [comment]
yes
